### ISSUE TITLE
Dapper.Crud.Extension on vs 2019

### ISSUE THREAD

**Issue by khaledpro2012** [thiagoloureiro/Dapper.Crud.Extension#14]
on vs 2019
Error during the operation: Compiler Errors :
Line 21,19	: Identifier expected
Line 21,19	: ; expected
Line 21,37	: ) expected
Line 21,37	: Type or namespace definition, or end-of-file expected
Line 21,39	: Type expected
Line 21,43	: Syntax error, '[' expected
Line 21,43	: Identifier expected
Line 21,46	: Identifier expected
Line 21,46	: Syntax error, ']' expected
Line 21,46	: { expected
Line 21,46	: A get or set accessor expected
Line 21,47	: } expected
Line 22,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 23,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 24,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 25,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
Line 26,19	: ; expected
Line 26,39	: Tuple must contain at least two elements.
Line 26,39	: ) expected
Line 26,39	: Type or namespace definition, or end-of-file expected
Line 26,41	: Type expected
Line 26,45	: Syntax error, '[' expected
Line 26,45	: Identifier expected
Line 26,48	: Identifier expected
Line 26,48	: Syntax error, ']' expected
Line 26,48	: { expected
Line 26,48	: A get or set accessor expected
Line 26,49	: } expected
Line 27,1	: A using clause must precede all other elements defined in the namespace except extern alias declarations
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 46
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 57
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73

**Comment by thiagoloureiro** [comment]
usually hidden files (not included in the project) causes this issues, the extension builds the whole folder and gets files even which are not included in the project, please verify if you have this.
Also if you can share the class are you trying to generate will be great.
