### ISSUE TITLE
Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater. Line 797,21

### ISSUE THREAD

**Issue by benalewis** [thiagoloureiro/Dapper.Crud.Extension#15]
Error during the operation: Compiler Errors :
Line 777,21	: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
Line 797,21	: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
Line 807,21	: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
Line 1063,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 46
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 57
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73

**Comment by thiagoloureiro** [comment]
@benalewis can you share the class that you're trying to generate? thanks

**Comment by thiagoloureiro** [comment]
Try to isolate the model classes in a different project, it's not recommended if you have the models inside the same project with another .cs files then can cause this issues.

**Comment by thiagoloureiro** [comment]
I managed to replicate the issue, I'm adding support to C# 7.1

**Comment by thiagoloureiro** [comment]
https://github.com/thiagoloureiro/Dapper.Crud.Extension/releases/tag/3.0.8
Please update to 3.0.8 and try again.
