### ISSUE TITLE
Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations

### ISSUE THREAD

**Issue by MikaelGyth** [thiagoloureiro/Dapper.Crud.Extension#19]
Hello, I get this error when I try to run this on a simple model.

```
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    namespace MyApp.Models
     {
        public class Organization
        {
             public int Id{ get; set; }
             public string Name { get; set; }
        }
    }
```

Using: Microsoft Visual Studio Professional 2019 Version 16.8.2

```
Error during the operation: Compiler Errors :
Line 1121,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
Line 1125,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
Line 1129,2	: Preprocessor directive expected
Line 1134,2	: Preprocessor directive expected
Line 1135,2	: Preprocessor directive expected
Line 1140,2	: Preprocessor directive expected
Line 1181,2	: Preprocessor directive expected
Line 1191,2	: Preprocessor directive expected
Line 1193,2	: Preprocessor directive expected
Line 1200,2	: Preprocessor directive expected
Line 1204,2	: Preprocessor directive expected
Line 1210,2	: Preprocessor directive expected
Line 1259,2	: Preprocessor directive expected
Line 1267,2	: Preprocessor directive expected
Line 1285,2	: Preprocessor directive expected
Line 1291,2	: Preprocessor directive expected
Line 1319,2	: Preprocessor directive expected
Line 1325,2	: Preprocessor directive expected
Line 1337,2	: Preprocessor directive expected
Line 1343,2	: Preprocessor directive expected
Line 1367,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
Line 1377,2	: Preprocessor directive expected
Line 1385,2	: Preprocessor directive expected
Line 1387,2	: Preprocessor directive expected
Line 1394,2	: Preprocessor directive expected
Line 1396,2	: Preprocessor directive expected
Line 1402,2	: Preprocessor directive expected
Line 1404,2	: Preprocessor directive expected
Line 1410,2	: Preprocessor directive expected
Line 1443,2	: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations
Line 1482,2	: Preprocessor directive expected
Line 1488,2	: Preprocessor directive expected
Line 1534,2	: Preprocessor directive expected
Line 1540,2	: Preprocessor directive expected
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 47
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 58
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73
```

**Comment by thiagoloureiro** [comment]
Hi! which type of project do you have? Xamarin or something similar?

**Comment by thiagoloureiro** [comment]
Most probably it's something inside your project that is making the component break, after you letting me know what type of project is I'll check here if I figure out.

![image](https://user-images.githubusercontent.com/29433794/100705171-0caab080-33a7-11eb-9413-14204bd5439b.png)

**Comment by thiagoloureiro** [comment]
can you check @MikaelGyth  if you have any class in your project using 
```[assembly: ``` and it's used before class and not name space?

![image](https://user-images.githubusercontent.com/29433794/100705571-b2f6b600-33a7-11eb-9f95-a8ab03e7b377.png)
