### ISSUE TITLE
Error thrown: 'IDbConnection' does not contain a definition for 'Query'

### ISSUE THREAD

**Issue by astrohart** [thiagoloureiro/Dapper.Crud.Extension#20]
I am trying to generate Dapper statements for my class

```
// ReSharper disable once RedundantUsingDirective

using Dapper;
using PostSharp.Patterns.Model;

namespace DemoLibrary
{
    /// <summary>
    ///     Record for a person.
    /// </summary>
    [NotifyPropertyChanged]
    public class PersonModel
    {
        /// <summary>
        ///     Gets or sets this person's first name.
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        ///     Gets this person's full name.
        /// </summary>
        public string FullName => $"{FirstName} {LastName}";

        /// <summary>
        ///     Gets or sets this person last name.
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        ///     ID of the person.
        /// </summary>
        public int PersonID { get; set; }

        /// <summary>Returns a string that represents the current object.</summary>
        /// <returns>A string that represents the current object.</returns>
        public override string ToString() => FullName;
    }
}
```

In the Dapper CRUD Generator, I tick the box for `PersonModel` and I only want to tick the box for `Insert` statement with AutoIncrement.

The **Ouput Log** text box shows:

```
Error during the operation: Compiler Errors :
Line 123,24	: 'IDbConnection' does not contain a definition for 'Query' and no extension method 'Query' accepting a first argument of type 'IDbConnection' could be found (are you missing a using directive or an assembly reference?)
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 47
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 58
   at Dapper.Crud.VSExtension.Helpers.ModelHelper.Generate(String[] content, String rawContent, String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\ModelHelper.cs:line 10
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Temp\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73
```

I am not sure how to fix.  I am not very skilled with Dapper.  Thanks in advance for any help.

**Comment by thiagoloureiro** [comment]
Hi @astrohart , looks like you have code (in other classes) that is not building properly because the component gets all classes to run the app (in case you reference other objects.

If your project is building normally check files that are not included in the solution.

I managed to run the Generator here with your class (I had to comment the ```  [NotifyPropertyChanged]``` because I don't have it here. (I also removed the two usings which are not needed (Dapper and PostSharp)

Result:

```
public class PersonModelRepository : IPersonModelRepository
{
    public async Task<IEnumerable<PersonModel>> SelectPersonModel()
    {
        // Select
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"SELECT FirstName, FullName, LastName, PersonID FROM [PersonModel]";

            return await db.QueryAsync<PersonModel>(sql, commandType: CommandType.Text);
        }
    }
    public async Task InsertPersonModel(PersonModel personmodel)
    {
        // Insert
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"INSERT INTO [PersonModel] (FirstName, FullName, LastName, PersonID) VALUES (@FirstName, @FullName, @LastName, @PersonID)";

            await db.ExecuteAsync(sql, new { FirstName = personmodel.FirstName, FullName = personmodel.FullName, LastName = personmodel.LastName, PersonID = personmodel.PersonID }, commandType: CommandType.Text);
        }
    }
    public async Task UpdatePersonModel(PersonModel personmodel)
    {
        // Update
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"UPDATE [PersonModel] SET FirstName = @FirstName, FullName = @FullName, LastName = @LastName, PersonID = @PersonID WHERE FirstName = @FirstName";

            await db.ExecuteAsync(sql, new { FirstName = personmodel.FirstName, FullName = personmodel.FullName, LastName = personmodel.LastName, PersonID = personmodel.PersonID }, commandType: CommandType.Text);
        }
    }
    public async Task DeletePersonModel(PersonModel personmodel)
    {
        // Delete
        using (var db = new SqlConnection(connstring))
        {
            string sql = @"DELETE FROM [PersonModel] WHERE FirstName = @FirstName";

            await db.ExecuteAsync(sql, new { personmodel.FirstName }, commandType: CommandType.Text);
        }
    }
}
public interface IPersonModelRepository
{
    Task<IEnumerable<PersonModel>> SelectPersonModel();
    Task InsertPersonModel(PersonModel personmodel);
    Task UpdatePersonModel(PersonModel personmodel);
    Task DeletePersonModel(PersonModel personmodel);
}
```

What I highly recommend you, check first if you have some code around which can cause the issue, if not, try to use the files inside another project/solution when you try to generate them. 👍 (without all project files which can cause conflicts)

Good luck! let me know how it goes.
