### ISSUE TITLE
Add Support to C# 10

### ISSUE THREAD

**Issue by as206em** [thiagoloureiro/Dapper.Crud.Extension#22]
Hi
it dosn't work with c# 10

Here is the error i'm gettig:

```
Error during the operation: Compiler Errors :
Line 562,29 : Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.
Line 577,29 : Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.
Line 592,29 : Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.
InnerException StackTrace at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 49
at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 61
at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73 Code using AutoMapper;
```

**Comment by thiagoloureiro** [comment]
Support added on 3.0.13, please check -> https://github.com/thiagoloureiro/Dapper.Crud.Extension/releases/tag/3.0.13

Changes:
https://github.com/thiagoloureiro/Dapper.Crud.Extension/commit/bc4e25cfe3b39ee31f21292a7e4c83a0cae7e79b

**Comment by as206em** [comment]
Hi
Thank you for the quick response,
unfortunately, it didn't work

```
Error during the operation: Compiler Errors :
Line 1,7	: The type or namespace name 'AutoMapper' could not be found (are you missing a using directive or an assembly reference?)
Line 2,7	: The type or namespace name 'CrossCutting' could not be found (are you missing a using directive or an assembly reference?)
Line 3,7	: The type or namespace name 'CrossCutting' could not be found (are you missing a using directive or an assembly reference?)
Line 114,31	: The name 'StatusCodes' does not exist in the current context
Line 115,27	: The type or namespace name 'IActionResult' could not be found (are you missing a using directive or an assembly reference?)
Line 58,56	: The type or namespace name 'FromQueryAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 58,56	: The type or namespace name 'FromQuery' could not be found (are you missing a using directive or an assembly reference?)
 InnerException  StackTrace    at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.BuildAssembly(String code) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 49
   at Dapper.Crud.VSExtension.Helpers.AssemblyHelper.ExecuteCode(String code, String namespacename, String classname, Boolean isstatic) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\Helpers\AssemblyHelper.cs:line 61
   at Dapper.Crud.VSExtension.frmExtension.GetPropertyInfos(String model) in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 277
   at Dapper.Crud.VSExtension.frmExtension.GenerateCrud() in C:\Projects\Dapper.Crud.Extension\Dapper.Crud.VSExtension\frmExtension.cs:line 73 Code using AutoMapper;
```

here is my csproj file

```
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="11.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.17.0" />
	</ItemGroup>

```


![image](https://user-images.githubusercontent.com/7923830/169211689-895b91d6-2312-4be5-9549-9117a61aa74f.png)
